# Generated by Django 5.1.3 on 2024-11-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='fullname',
            new_name='name',
        ),
    ]
